version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-productos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql